### ISSUE TITLE
warnings from outside test functions

### ISSUE THREAD

**Issue by davidszotten** [fschulze/pytest-warnings#8]
would it be possible to collect/show warnings happening outside of test functions?

e.g. with 
```
import warnings

warnings.warn("In test module")


def test_foo():
    warnings.warn("In test function")
```

i get
```
 pytest-warning summary 
WW0 in test/test_foo.py:5 the following warning was recorded:
 test/test_foo.py:7: UserWarning: In test function
  warnings.warn("In test function")
```

Happening to me in practice with a django project, where a bunch of deprecation warnings from url and model declarations happen at import time and so are missed

**Comment by twmr** [comment]
@fschulze, should feature requests like this one now that pytest-warnings has been integrated into upstream pytest be moved to the pytest-dev/pytest issue tracker?

**Comment by fschulze** [comment]
I'd say so. I see no good reason to maintain this plugin for older pytest versions.

**Comment by fschulze** [comment]
This plugin has been integrated into pytest for long enough.
